# Generated by Django 2.2.4 on 2019-08-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellog',
            name='plan_time',
            field=models.DateField(null=True),
        ),
    ]
